wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1678786285.298985
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.9.16
      5: 0.13.11
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 32
dataset_ratio_split:
  desc: null
  value:
  - 0.4
  - 0.4
  - 0.2
device_type:
  desc: null
  value: cpu
ealry_stopping_count:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.001
max_epoch:
  desc: null
  value: 30
notes:
  desc: null
  value: Welcome test
